:sectnums:
:xrefstyle: short

= Test plan for ext oneapi current device

This is a test plan for the device selector as described in SYCL 2020 revision 9 specification.

Estimated development time is one day.

== Testing scope

=== Backend coverage

All the tests described below are not backend-specific and are performed for any SYCL backend.

=== Device coverage

All tests construct a test device for which conformance is assessed. All of the tests described below are performed only on the default device that
can be selected on the CTS command line.

== Tests

=== Feature test macro

All of the tests should use `#ifdef SYCL_EXT_ONEAPI_CURRENT_DEVICE` so they can be skipped
if feature is not supported.

=== Function `get_current_device`

1. Positive case. This test can be performed by seting default device, calling from a host thread the function sycl::ext::oneapi::experimental::this_thread::get_current_device 
and compare function output with the default device which was set earlier, check thread ID 

2. Negative case. Implement the same as positive but call function from kernel(not host) code. Use XFAIL to detect compilation error

=== Function `set_current_device`

1. Positive case. This test can be performed by checking default device, calling from a host thread the function sycl::ext::oneapi::experimental::this_thread::set_current_device,
getting default device and compare it with the previous value, check thread ID 

2. Negative case. Implement the same as positive but call function from kernel(not host) code. Use XFAIL to detect compilation error
