#!/usr/bin/env bash
set -o errexit -o pipefail -o noclobber -o nounset
cmake . -G Ninja -B build \
    -DCMAKE_CXX_COMPILER_LAUNCHER=ccache \
    -DSYCL_IMPLEMENTATION=ProtoSYCL \
    -DCMAKE_PREFIX_PATH=/sycl \
    -DCMAKE_BUILD_TYPE=Release \
    -DSYCL_CTS_ENABLE_FULL_CONFORMANCE=OFF \
    -DSYCL_CTS_ENABLE_OPENCL_INTEROP_TESTS=OFF \
    -DSYCL_CTS_ENABLE_CUDA_INTEROP_TESTS=OFF \
    -DSYCL_CTS_ENABLE_HALF_TESTS=ON \
    -DSYCL_CTS_ENABLE_DEPRECATED_FEATURES_TESTS=ON \
    -DSYCL_CTS_ENABLE_FEATURE_SET_FULL=ON \
    $@
