# Go to https://github.com/intel/llvm/pkgs/container/llvm%2Fsycl_ubuntu2204_nightly for the latest docker image tag
FROM ghcr.io/intel/llvm/sycl_ubuntu2204_nightly:no-drivers-c9219ce7232da9bc10d50dff8a1858540b292df5

COPY configure.sh /scripts/
